### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by oussamabonnor1** [oussamabouchikhi/crwn-clothing#1]
Unable to render the contact page.
Screenshot:
![image](https://user-images.githubusercontent.com/17766221/90542752-e0b34880-e184-11ea-84c5-fd9ff55069b5.png)

Unable to access the register or any authentication features mentioned in the readMe.md

**Comment by oussamabouchikhi** [comment]
@oussamabonnor1 thanks for reporting that, I didn't implement the contact page so it's an odd one but for the registration I tested it many times & it was working perfectly the problem may be on Heroku I will try to solve the problem soon
